
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace DotNetGadgeteerCam
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module defintions
		Gadgeteer.Modules.GHIElectronics.Camera _camera;
		Gadgeteer.Modules.GHIElectronics.SDCard _sdCard;
		Gadgeteer.Modules.GHIElectronics.MulticolorLed _led;
		Gadgeteer.Modules.GHIElectronics.Button _wifiButton;
		Gadgeteer.Modules.GHIElectronics.WiFi_RS21 _wifi;
		Gadgeteer.Modules.Seeed.Compass _compass;
		Gadgeteer.Modules.GHIElectronics.Ethernet_J11D _ethernet;
		Gadgeteer.Modules.GHIElectronics.Button _ethernetButton;

		public static void Main()
        {
			//Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
			program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
			// Initialize GTM.Modules and event handlers here.		
			_camera = new GTM.GHIElectronics.Camera(3);
		
			_wifiButton = new GTM.GHIElectronics.Button(4);
		
			_sdCard = new GTM.GHIElectronics.SDCard(5);
		
			_ethernet = new GTM.GHIElectronics.Ethernet_J11D(7);
		
			_ethernetButton = new GTM.GHIElectronics.Button(8);
		
			_wifi = new GTM.GHIElectronics.WiFi_RS21(9);
		
			_compass = new GTM.Seeed.Compass(10);
		
			_led = new GTM.GHIElectronics.MulticolorLed(11);

        }
    }
}
